version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      DB_HOST: mysql_server
      DB_PORT: 3306
      DB_USER: sysdes
      DB_PASSWORD: sysdes
      DB_NAME: sysdes_todolist_db
    volumes:
      - .:/go/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sysdes_todolist_db
      MYSQL_USER: sysdes
      MYSQL_PASSWORD: sysdes
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      #- ./docker/db/data:/var/lib/mysql  ## uncomment to keep the data
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_client
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_server
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    depends_on:
      - db
